import Head from "next/head";
import { styled } from "styled-components";
import { Button } from "@bennytestui1/styles";
// const StyledButton = styled.div`
// 	width: 100px;
// 	height: 100px;
// 	display: flex;
// 	justify-content: center;
// 	align-items: center;
// 	background-color: #000;
// `;
export default function Home() {
	return (
		<>
			<Head>
				<title>Responsive Navbar</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Button
				width="100px"
				height="100px"
				backgroundColor="#000"
				color="#fff"
			/>
		</>
	);
}
